branches:
  only:
    - master
    - /^(fix|feat|feature|dev|tmp)\//
language: node_js
node_js:
  - "node"
  - "8"
  - "6"
sudo: false
install:
  - npm install
  - npm install -g codecov
script:
  - npm run coverage:test
after_success:
  - npm run coverage:report && codecov
